# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
name: cron
on:
  push:
    branches:
      - alpha
  schedule:
    # * is a special character in YAML so you have to quote this string
    # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.htm
    # minute [0,59]
    # hour [0,23]
    # day of the month [1,31]
    # month of the year [1,12]
    # day of the week ([0,6] with 0=sunday)
    - cron: "28 * * * *"
  workflow_dispatch:
env:
  MY_GITHUB_REPOSITORY: kaizhu256/betadog
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$(date -u +"%Y-%m-%d %TZ")" # "
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4
        with:
          repository: ${{ env.MY_GITHUB_REPOSITORY }}
          token: ${{ secrets.MY_GITHUB_TOKEN }}
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # https://github.com/actions/setup-python
      - uses: actions/setup-python@v4
        with:
          cache: "pip"
          python-version: "3.10"
      # cleanup repo
      - run: sh jslint_ci.sh shGitCommitPushOrSquash "" 100
      # run cron
      - run: sh jslint_ci.sh shCronCustom
